#!/usr/bin/env zsh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
  echo "${bg[yellow]}${fg[black]} Warning: You should not commit directly to $branch branch, it is bad practice! ${reset_color}"
fi
